# Generated by Django 5.2.1 on 2026-03-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0007_add_cancel_loan_password_reset_doc_verify"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="disbursed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="disbursement_account_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="loan",
            name="disbursement_account_number",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="loan",
            name="disbursement_method",
            field=models.CharField(
                choices=[
                    ("bank_transfer", "Bank Transfer"),
                    ("gcash", "GCash"),
                    ("maya", "Maya"),
                    ("cash_pickup", "Cash Pickup"),
                ],
                default="bank_transfer",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="disbursement_reference",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="loan",
            name="disbursement_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("disbursed", "Disbursed")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("gcash", "GCash"),
                    ("maya", "Maya"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
