# Generated by Django 5.2.1 on 2026-03-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_user_gcash_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantype',
            name='required_documents',
            field=models.JSONField(default=list),
        ),
    ]
