# Generated by Django 5.2.1 on 2026-03-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_add_required_documents_to_loantype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowerdocument',
            name='document_type',
            field=models.CharField(choices=[('id', 'ID'), ('income_proof', 'Proof of Income'), ('government_id', 'Government ID'), ('student_id', 'Student ID'), ('business_permit', 'Business Permit'), ('business_owner_id', 'Business Owner ID'), ('proof_of_revenue', 'Proof of Monthly Revenue')], max_length=20),
        ),
    ]
