# Generated by Django 5.2.1 on 2026-03-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0014_user_approval_status_user_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.FileField(blank=True, upload_to='profile_photos/'),
        ),
    ]
