# Generated by Django 5.2.1 on 2026-04-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0015_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='applicant_count',
            field=models.CharField(blank=True, choices=[('one', 'Just Me'), ('two', '2 of Us'), ('many', '3+ People')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='application_purpose',
            field=models.CharField(blank=True, choices=[('purchase', 'Purchase'), ('refinance', 'Refinance'), ('both', 'Both')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='loan',
            name='contact_phone_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
