# Generated by Django 5.2.1 on 2026-04-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0016_loan_applicant_count_loan_application_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowerdocument',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='borrowerdocument',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='uploaded', max_length=20),
        ),
    ]
