from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (
    AdminDashboardView,
    AdminLoanDecisionView,
    AdminLoanListView,
    AdminLoanTypeDetailView,
    AdminLoanTypeListCreateView,
    AdminReportsView,
    AdminTransactionView,
    AdminUserDetailView,
    AdminUserListView,
    BorrowerAccountRequestListCreateView,
    BorrowerCancelLoanView,
    BorrowerDashboardView,
    BorrowerDocumentListCreateView,
    BorrowerLoanListCreateView,
    BorrowerNotificationListView,
    BorrowerNotificationReadView,
    ChangePasswordView,
    ForgotPasswordView,
    HealthCheckView,
    BorrowerPaymentListView,
    BorrowerPaymentSubmissionListCreateView,
    LoginView,
    MeView,
    OfficerApprovePaymentSubmissionView,
    OfficerApplicationListView,
    OfficerApprovedLoanListView,
    OfficerBorrowerDocumentsView,
    OfficerBorrowerListView,
    OfficerBorrowerLoansView,
    OfficerBorrowerPaymentsView,
    OfficerLoanDisbursementView,
    OfficerLoanDecisionView,
    OfficerPaymentCreateView,
    OfficerPaymentListView,
    OfficerPaymentSubmissionListView,
    OfficerRejectPaymentSubmissionView,
    OfficerRejectDocumentView,
    OfficerToggleBorrowerStatusView,
    OfficerVerifyDocumentView,
    PublicLoanTypeListView,
    PublicOverviewView,
    RegisterView,
    ResetPasswordView,
    SendEmailVerificationCodeView,
    VerifyEmailCodeView,
    XenditPayoutWebhookView,
)

urlpatterns = [
    path("health/", HealthCheckView.as_view(), name="health-check"),
    path("auth/register/", RegisterView.as_view(), name="register"),
    path("auth/login/", LoginView.as_view(), name="login"),
    path("auth/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("auth/me/", MeView.as_view(), name="me"),
    path("auth/verification/send/", SendEmailVerificationCodeView.as_view(), name="send-verification-code"),
    path("auth/verification/verify/", VerifyEmailCodeView.as_view(), name="verify-email-code"),
    path("auth/forgot-password/", ForgotPasswordView.as_view(), name="forgot-password"),
    path("auth/reset-password/", ResetPasswordView.as_view(), name="reset-password"),
    path("auth/change-password/", ChangePasswordView.as_view(), name="change-password"),
    path("public/loan-types/", PublicLoanTypeListView.as_view(), name="public-loan-types"),
    path("public/overview/", PublicOverviewView.as_view(), name="public-overview"),
    path("borrower/dashboard/", BorrowerDashboardView.as_view(), name="borrower-dashboard"),
    path("borrower/loans/", BorrowerLoanListCreateView.as_view(), name="borrower-loans"),
    path("borrower/loans/<int:pk>/cancel/", BorrowerCancelLoanView.as_view(), name="borrower-cancel-loan"),
    path("borrower/payments/", BorrowerPaymentListView.as_view(), name="borrower-payments"),
    path("borrower/payment-submissions/", BorrowerPaymentSubmissionListCreateView.as_view(), name="borrower-payment-submissions"),
    path("borrower/documents/", BorrowerDocumentListCreateView.as_view(), name="borrower-documents"),
    path("borrower/notifications/", BorrowerNotificationListView.as_view(), name="borrower-notifications"),
    path("borrower/notifications/<int:pk>/read/", BorrowerNotificationReadView.as_view(), name="borrower-notification-read"),
    path("borrower/account-requests/", BorrowerAccountRequestListCreateView.as_view(), name="borrower-account-requests"),
    path("officer/applications/", OfficerApplicationListView.as_view(), name="officer-applications"),
    path("officer/applications/<int:pk>/decision/", OfficerLoanDecisionView.as_view(), name="officer-loan-decision"),
    path("officer/borrowers/", OfficerBorrowerListView.as_view(), name="officer-borrowers"),
    path("officer/borrowers/<int:pk>/toggle-active/", OfficerToggleBorrowerStatusView.as_view(), name="officer-toggle-borrower-status"),
    path("officer/borrowers/<int:borrower_id>/documents/", OfficerBorrowerDocumentsView.as_view(), name="officer-borrower-documents"),
    path("officer/borrowers/<int:borrower_id>/loans/", OfficerBorrowerLoansView.as_view(), name="officer-borrower-loans"),
    path("officer/borrowers/<int:borrower_id>/payments/", OfficerBorrowerPaymentsView.as_view(), name="officer-borrower-payments"),
    path("officer/documents/<int:pk>/verify/", OfficerVerifyDocumentView.as_view(), name="officer-verify-document"),
    path("officer/documents/<int:pk>/reject/", OfficerRejectDocumentView.as_view(), name="officer-reject-document"),
    path("officer/approved-loans/", OfficerApprovedLoanListView.as_view(), name="officer-approved-loans"),
    path("officer/disbursements/record/", OfficerLoanDisbursementView.as_view(), name="officer-record-disbursement"),
    path("webhooks/xendit/payouts/", XenditPayoutWebhookView.as_view(), name="xendit-payout-webhook"),
    path("officer/payments/", OfficerPaymentListView.as_view(), name="officer-payments"),
    path("officer/payments/record/", OfficerPaymentCreateView.as_view(), name="officer-record-payment"),
    path("officer/payment-submissions/", OfficerPaymentSubmissionListView.as_view(), name="officer-payment-submissions"),
    path("officer/payment-submissions/<int:pk>/approve/", OfficerApprovePaymentSubmissionView.as_view(), name="officer-approve-payment-submission"),
    path("officer/payment-submissions/<int:pk>/reject/", OfficerRejectPaymentSubmissionView.as_view(), name="officer-reject-payment-submission"),
    path("admin/dashboard/", AdminDashboardView.as_view(), name="admin-dashboard"),
    path("admin/reports/", AdminReportsView.as_view(), name="admin-reports"),
    path("admin/transactions/", AdminTransactionView.as_view(), name="admin-transactions"),
    path("admin/loans/", AdminLoanListView.as_view(), name="admin-loans"),
    path("admin/loans/<int:pk>/decision/", AdminLoanDecisionView.as_view(), name="admin-loan-decision"),
    path("admin/users/", AdminUserListView.as_view(), name="admin-users"),
    path("admin/users/<int:pk>/", AdminUserDetailView.as_view(), name="admin-user-detail"),
    path("admin/loan-types/", AdminLoanTypeListCreateView.as_view(), name="admin-loan-types"),
    path("admin/loan-types/<int:pk>/", AdminLoanTypeDetailView.as_view(), name="admin-loan-type-detail"),
]
